# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0004_auto_20170922_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
