# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='pic_folder/'),
        ),
    ]
