# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170922_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
