# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20170922_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default='none.png', null=True, upload_to=''),
        ),
    ]
