# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20170922_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
