# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
    ]
