# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20170922_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
