# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('movies', '0012_review_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('movie', 'user')]),
        ),
    ]
