# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20171110_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(),
        ),
    ]
